### ISSUE TITLE
Please add a license file and consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [AndreyPuzanov/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

It also doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by AndreyPuzanov** [comment]
I renamed repository and added a LICENSE.md file.

**Comment by unixorn** [comment]
Thanks!
